image: "julia:1"

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"
  JULIA_NUM_THREADS: '8'

cache:
  paths:
    - .julia/
    
stages:
  - build
  - test

build:
  stage: build
  tags:
    - 'p6000'
  script:
    - curl https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz -o julia.tar.gz
    - unp julia.tar.gz
    - export PATH="$(pwd)/julia-1.1.1/bin:$PATH"
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg; Pkg.build(); using OrdinaryDiffEq"
  only:
  - master
  - tags
  - external
  - pushes
  artifacts:
    untracked: true
    paths:
      - .julia/**/*
      - julia-1.1.1/**/*

test-GPU:
  stage: test
  tags:
    - 'p6000'
  dependencies:
    - build
  variables:
    GROUP: "GPU"
  script:
    - export PATH="$(pwd)/julia-1.1.1/bin:$PATH"
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg; Pkg.add(\"CuArrays\");
                          Pkg.test(;coverage = true);"
  only:
  - master
  - tags
  - external
  - pushes
  artifacts:
    untracked: true
    paths:
      - .julia/**/*
      - julia-1.1.1/**/*
